name: Code Formatting

on: [push, pull_request]

jobs:
  format_code:
    name: runner / formatters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Run isort
        uses: isort/isort-action@v1.1.0
        id: action_isort
        with:
          requirements-files: "requirements.txt requirements-test.txt"
      
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1.3.3
        id: action_black
        with:
          black_args: "--line-length 120 ."

      - name: Create Pull Request
        if: steps.action_isort.outputs.is_formatted == 'true' || steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format Python code with isort and psf/black"
          commit-message: ":art: Format Python code with isort and psf/black"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [isort](https://github.com/PyCQA/isort) and [psf/black](https://github.com/psf/black) formatters to fix these issues.
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/code-formatting
